spring.application.name=api-gateway
server.port=9000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/spring-microservices-security-realm
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8180/realms/spring-microservices-security-realm/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/spring-microservices-security-realm/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8180/realms/spring-microservices-security-realm/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:8180/realms/spring-microservices-security-realm/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.registration.keycloak.client-id=api-gateway-swagger-ui
spring.security.oauth2.client.registration.keycloak.client-secret=${API_GATEWAY_SWAGGER_CLIENT_SECRET:api-gateway-swagger-secret}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


# Actuator Endpoints
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=4
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=2

resilience4j.circuitbreaker.instances.productServiceCircuitBreaker.baseConfig=default
resilience4j.circuitbreaker.instances.productServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ordersServiceCircuitBreaker.baseConfig=default
resilience4j.circuitbreaker.instances.ordersServiceCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.baseConfig=default
resilience4j.circuitbreaker.instances.inventoryServiceCircuitBreaker.registerHealthIndicator=true

# Resilience4j Time out Configuration
resilience4j.timelimiter.configs.default.timeoutDuration=3s
resilience4j.timelimiter.instances.productServiceCircuitBreaker.baseConfig=default
resilience4j.timelimiter.instances.ordersServiceCircuitBreaker.baseConfig=default
resilience4j.timelimiter.instances.inventoryServiceCircuitBreaker.baseConfig=default

# Resilience4j Retry Configuration
resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=2s
